databaseChangeLog:
  - changeSet:
      id: 004-create-applications
      author: Viktoriya
      changes:
        - createTable:
            tableName: applications
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: property_id
                  type: INT
                  constraints:
                    foreignKeyName: fk_applications_property
                    references: properties(id)
              - column:
                  name: tenant_id
                  type: INT
                  constraints:
                    foreignKeyName: fk_applications_tenant
                    references: users(id)
              - column:
                  name: owner_id
                  type: INT
                  constraints:
                    foreignKeyName: fk_applications_owner
                    references: users(id)
              - column:
                  name: message
                  type: TEXT
              - column:
                  name: status
                  type: VARCHAR(50)
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: deleted
                  type: BOOLEAN
                  defaultValue: "false"
