spring:
  application:
    name: rental-platform
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: test
  cloud:
    config:
      fail-fast: true
    compatibility-verifier:
      enabled: false
  mail:
    host: smtp.mailtrap.ru
    port: 2525
    username: bakofqkd9f3bg
    password: baymojd3wa8ey

server:
  port: 8080