spring:
  application:
    name: rental-platform
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: test
  cloud:
    config:
      fail-fast: true
    compatibility-verifier:
      enabled: false

server:
  port: 8080