spring:
  application:
    name: rental-platform
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: dev
  cloud:
    config:
      fail-fast: true

server:
  port: 8080