spring:
  application:
    name: rental-platform
  mail:
    host: smtp.mailtrap.ru
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  config:
    import: optional:file:./local.properties
server:
  port: 8080

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration: 21600000