spring:
  application:
    name: rental-platform
  mail:
    host: smtp.mailtrap.ru
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  config:
    import: optional:file:./local.properties
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8081/realms/myrealm/protocol/openid-connect/token/introspect
          client-id: property-service
          client-secret: ${KEYCLOAK_SECRET}
server:
  port: 8080

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration: 21600000

minio:
  url: http://localhost:9000
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}
  bucket: images